### ISSUE TITLE
Test Kit Evaluation Data

### ISSUE THREAD

**Issue by rik030** [Voldemort108X/myops20#1]
Hello Sir,
How did you access the test kit evaluation data to evaluate your model performance since the dataset is encrypted?

**Comment by Voldemort108X** [comment]
Hi, thanks for the comment. The organizers sent us the test input data and the metrics are computed upon that. Please reach out directly to the organizers if you have any questions regarding the testing. Thanks.

**Comment by rik030** [comment]
Hello Sir,
Do you have the ground truths for test data?

**Comment by Voldemort108X** [comment]
Hi, unfortunately, the ground truths of test data are not provided.

**Comment by rik030** [comment]
Hello Sir, 
Then how did you proceed with the test data scores?

**Comment by Voldemort108X** [comment]
Hi, the test scores are evaluated by organizers.
